### ISSUE TITLE
add .gitignore with forgae initialization

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#208]

**Comment by maptuhec** [comment]
@thepiwo you want to generate .gitignore file when creating a new project with Forgae right?

**Comment by thepiwo** [comment]
Yes, it can be delivered as artifact as well

**Comment by maptuhec** [comment]
Do you think we should add something specific to the .gitignore or just a black file?

**Comment by thepiwo** [comment]
Ignoring anything that should not be committed to a repository, e.g. node modules and eventually forgae history

**Comment by marc0olo** [comment]
I think there is currently a problem with that when initializing a new project. see here:
```
marc0olo@N151ZU:~/git/aeternity/universe-one-hackathon/contracts$ aeproject init
===== Initializing AEproject =====
===== Installing aepp-sdk =====
===== Installing AEproject locally =====
===== Installing yarn locally =====
===== Creating project file & dir structure =====
===== Creating contracts directory =====
===== Creating tests directory =====
===== Creating integrations directory =====
===== Creating deploy directory =====
===== Creating docker directory =====
==== Adding additional files ====
ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/aeproject/aeproject-init/artifacts/.gitignore'
{ Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/aeproject/aeproject-init/artifacts/.gitignore'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/usr/local/lib/node_modules/aeproject/node_modules/graceful-fs/polyfills.js:308:16)
    at checkStats (/usr/local/lib/node_modules/aeproject/node_modules/fs-extra/lib/copy-sync/copy-sync.js:171:22)
    at checkPaths (/usr/local/lib/node_modules/aeproject/node_modules/fs-extra/lib/copy-sync/copy-sync.js:183:31)
    at Object.copySync (/usr/local/lib/node_modules/aeproject/node_modules/fs-extra/lib/copy-sync/copy-sync.js:25:20)
    at copyFileOrDir (/usr/local/lib/node_modules/aeproject/node_modules/aeproject-utils/utils/fs-utils.js:30:8)
    at addIgnoreFile (/usr/local/lib/node_modules/aeproject/aeproject-init/init.js:141:5)
    at createAEprojectProjectStructure (/usr/local/lib/node_modules/aeproject/aeproject-init/init.js:54:5)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/usr/local/lib/node_modules/aeproject/aeproject-init/artifacts/.gitignore' }
```
