### ISSUE TITLE
aeproject init --update fails with 5.0.2

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#282]
```
(node:30531) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at uninstallForgaeDependencies (/home/philipp/.npm-global/lib/node_modules/aeproject/aeproject-init/init.js:114:14)
    at updateAEprojectProjectLibraries (/home/philipp/.npm-global/lib/node_modules/aeproject/aeproject-init/init.js:69:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (/home/philipp/.npm-global/lib/node_modules/aeproject/aeproject-init/init.js:33:9)
    at async Command.<anonymous> (/home/philipp/.npm-global/lib/node_modules/aeproject/commands.js:42:13)
```

**Comment by HristiyanG** [comment]
Hey @thepiwo ,

Your issue should be resolved in the latest version @2.1.0 of **aeproject**

Cheers!
