### ISSUE TITLE
aeproject compiler fails (on updated project)

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-aeproject-js#284]
```
→ aeproject compiler
===== Starting Compiler =====
.(node:8134) UnhandledPromiseRejectionWarning: Error: Process exited with code 1
    at ChildProcess.done (/home/philipp/.npm-global/lib/node_modules/aeproject/node_modules/promisify-child-process/index.js:42:47)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by HristiyanG** [comment]
Hey Piwo,

We struggled to reproduce that particular problem of yours. Could you give us some hints so we could better look into it? 

Hris

**Comment by thepiwo** [comment]
It's 20 days ago, I think I'll be unable to reproduce the environment at the time

**Comment by HristiyanG** [comment]
Hey Piwo,
 
I am closing this. If you encounter such a problem, we'll reopen it
